### ISSUE TITLE
Could Matcher be changed to be typed as Matcher<T>?

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/matcher#37]
Specifically, this allows strongly-typed assurances when creating specialized matchers:

``` dart
abstract class StringMatcher extends Matcher<String> {}
```

I don't _think_ this is a breaking change, unless we specifically want to allow something like:

``` dart
expect(5, isNot(equalsIgnoringCase('5')))
```

---

*Added after the fact by @nex3*

Blocking issues (see comments for details):

* [ ] https://github.com/dart-lang/sdk/issues/27917 - changes in strong mode inference. Closed as not planned - too breaking
* [ ] https://github.com/dart-lang/language/issues/83 - add support for union types
* [X] https://github.com/dart-lang/language/issues/731 - flow information between arguments during inference.

**Comment by jacehensley-wf** [comment]
I would also like to see something like this. In strong mode you cannot override the types of params in methods. Having something like this would be great.

To be able to use the `item` param, for instance, in a typed manner you have to cast it using `as`.

```dart
class StringMatcher<T extends String> extends Matcher<T> {
  @override
  bool matches(T item, Map matchState) {
    // Use a String method
    if (item.contains('whatever') return true;
  }
}
```

Vs.

 ```dart
class StringMatcher extends Matcher {
  @override
  bool matches(dynamic _item, Map matchState) {
    item = _item as String;

    // Use a String method
    if (item.contains('whatever') return true;
  }
}
```

**Comment by matanlurey** [comment]
@jacehensley-wf FWIW, I've been using this pattern for now:

```dart
@override
bool matches(item, _) {
  if (item is String) {
    return item.contains('whatever');
  }
  return false;
}
```

Still not preferable since you get runtime errors, not static errors.

**Comment by zoechi** [comment]
@jacehensley-wf you can now override parameters when you add the `@checked` annotation https://pub.dartlang.org/packages/meta (1.0.3)

**Comment by jacehensley-wf** [comment]
Hmm, I thought I tried that. I'll try it again.

Yeah I am still getting this error:

```
Invalid override. The type of ClassNameMatcher.matches ((String, Map<dynamic, dynamic>) → bool) is not a subtype of Matcher.matches ((dynamic, Map<dynamic, dynamic>) → bool).
```

When doing this:

```dart
bool matches(@checked String className, Map matchState)
```

I'm on Dart 1.19.1 using Atom if that matters.

**Comment by matanlurey** [comment]
You might need the latest Dart stable or even development branch.

**Comment by jacehensley-wf** [comment]
Thanks, I'll try it out on those versions.

**Comment by nex3** [comment]
I like this idea a lot, especially since strong mode provides a lot more benefits for having nice types everywhere. However, in order to make this useful, we'd need to integrate it into `expect()`, which would require a few features we don't have yet. In particular:

* dart-lang/sdk#27917. Without this, Dart will just infer `expect<Object>()` for any cases where the matcher doesn't match the value.
* dart-lang/sdk#4938. The second parameter to `expect()`, as well as most parameters that take matchers, allow either a matcher or a raw value. In order to have any inference at all, we'd need to be able to express `T | Matcher<T>`.

**Comment by matanlurey** [comment]
Cool. Stalking those issues :)

**Comment by jacehensley-wf** [comment]
@nex3 I think there is still value in adding a generic parameter to `Matcher` even with out those other issues. I do agree that those with those other issues it would make this much more meaningful.

**Comment by zoechi** [comment]
Just some update:

> @jacehensley-wf you can now override parameters when you add the @checked annotation 

`@checked` was kinda replaced by `covariant`

**Comment by kevmoo** [comment]
@nex3 any more thoughts on this?

**Comment by nex3** [comment]
Neither of the blocking issues are closed, so... no?

**Comment by nex3** [comment]
I believe this is also blocked on dart-lang/sdk/issues/25490, since it requires that type information flow between arguments of `expect()`.

**Comment by natebosch** [comment]
Closing this as not planned. This appears to rely on language features we are unlikely to get anytime soon, and we're instead delivering the benefit this would have brought in a new package with a different design. https://pub.dev/packages/checks
